AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Pipeline asíncrono de imágenes con SAM

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Architectures: [x86_64]

Resources:
  # 1. Storage
  AppStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "img-lab-${AWS::AccountId}-${AWS::Region}"

  # 2. Messaging Queue
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 70

  SignerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: signer.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref AppStorageBucket
      Policies:
        - S3ReadPolicy: { BucketName: !Ref AppStorageBucket }
        - S3WritePolicy: { BucketName: !Ref AppStorageBucket }
      Events:
        # Endpoint para obtener URL de descarga (GET)
        GetImageEvent:
          Type: Api
          Properties:
            Path: /image
            Method: get
        # Endpoint para obtener URL de subida (POST)
        UploadImageEvent:
          Type: Api
          Properties:
            Path: /image
            Method: post